[build]
  publish = "."
  command = ""

[[scheduled.functions]]
  name = "daily-tip"
  cron = "0 5 * * *" # 05:00 UTC ≈ 07:00 SAST

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
