[build]
  publish = "."
  command = ""

# Schedules (UTC). 06:00 UTC ≈ 08:00 SAST
[[scheduled.functions]]
  name = "checklist-reminder"
  cron = "0 6 * * 1-5"   # Weekdays 08:00 SAST

[[scheduled.functions]]
  name = "weekly-summary"
  cron = "0 6 * * 1"     # Mondays 08:00 SAST

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
